# Generated by Django 3.2 on 2024-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_keyword', models.CharField(max_length=100, verbose_name='搜索关键词')),
                ('name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('description', models.TextField(verbose_name='资源描述')),
                ('link', models.CharField(max_length=100, verbose_name='资源链接')),
                ('size', models.CharField(max_length=20, verbose_name='资源大小')),
                ('access', models.BooleanField(verbose_name='是否可访问')),
                ('network', models.CharField(choices=[('阿里', '阿里网盘'), ('百度', '百度网盘'), ('夸克', '夸克网盘'), ('迅雷', '迅雷网盘')], max_length=10, verbose_name='网盘类别')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='电影别名')),
                ('detail', models.TextField(default=None, verbose_name='资源详情')),
                ('rate', models.FloatField(default=None, verbose_name='豆瓣评分')),
            ],
            options={
                'verbose_name': '电影列表',
                'verbose_name_plural': '电影列表',
            },
        ),
    ]
