# Generated by Django 3.2 on 2024-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(max_length=400, verbose_name='资源链接'),
        ),
    ]
