# Generated by Django 3.2 on 2024-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('search_keyword', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='搜索关键词')),
                ('poster', models.ImageField(blank=True, default=None, null=True, upload_to='movies', verbose_name='电影海报')),
            ],
        ),
    ]
